/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fitnesstrackerproject;

import javax.swing.JOptionPane;
import java .sql.*;

/**
 *
 * @author hp
 */
public class CalorieAndBMI extends javax.swing.JFrame {

    /**
     * Creates new form Form7
     */
    public CalorieAndBMI() {
        initComponents();
    }
public interface CalorieCalculator {
    double calculateBMR(double weight, int height, int age);
    double calculateTDEE(double BMR);
}
public class MaleCalorieCalculator implements CalorieCalculator {
    @Override
    public double calculateBMR(double weight, int height, int age) {
        return 88.362 + (13.397 * weight) + (4.799 * height) - (5.677 * age);
    }

    @Override
    public double calculateTDEE(double BMR) {
        return BMR * 1.55;
    }
}
public class FemaleCalorieCalculator implements CalorieCalculator {
    @Override
    public double calculateBMR(double weight, int height, int age) {
        return 447.593 + (9.247 * weight) + (3.098 * height) - (4.330 * age);
    }

    @Override
    public double calculateTDEE(double BMR) {
        return BMR * 1.55;
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        bbuuton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        HEIGHTFIELD = new javax.swing.JTextField();
        WEIGHTFEILD = new javax.swing.JTextField();
        AGEFIELD = new javax.swing.JTextField();
        CALCULATEBUTTON = new javax.swing.JButton();
        MRADIO = new javax.swing.JRadioButton();
        FRADIO = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        ANSWETEXTAREA = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bbuuton.setFont(new java.awt.Font("Lucida Handwriting", 1, 10)); // NOI18N
        bbuuton.setText("BACK");
        bbuuton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbuutonActionPerformed(evt);
            }
        });
        jPanel1.add(bbuuton, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 420, -1, -1));

        jLabel1.setFont(new java.awt.Font("Lucida Handwriting", 1, 14)); // NOI18N
        jLabel1.setText("CALORIE & BMI COUNTER:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 210, 230, 20));

        jLabel2.setFont(new java.awt.Font("Lucida Handwriting", 1, 10)); // NOI18N
        jLabel2.setText("HEIGHT(cm)");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 290, 80, -1));

        jLabel3.setFont(new java.awt.Font("Lucida Handwriting", 1, 10)); // NOI18N
        jLabel3.setText("WEIGHT(kg)");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 260, 80, -1));

        jLabel4.setFont(new java.awt.Font("Lucida Handwriting", 1, 10)); // NOI18N
        jLabel4.setText("AGE");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 320, -1, -1));

        HEIGHTFIELD.setFont(new java.awt.Font("Calibri Light", 0, 10)); // NOI18N
        jPanel1.add(HEIGHTFIELD, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 320, 50, 20));

        WEIGHTFEILD.setFont(new java.awt.Font("Calibri", 0, 10)); // NOI18N
        WEIGHTFEILD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WEIGHTFEILDActionPerformed(evt);
            }
        });
        jPanel1.add(WEIGHTFEILD, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 260, 50, 20));

        AGEFIELD.setFont(new java.awt.Font("Calibri", 0, 10)); // NOI18N
        AGEFIELD.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.add(AGEFIELD, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 290, 50, 20));

        CALCULATEBUTTON.setFont(new java.awt.Font("Lucida Handwriting", 1, 8)); // NOI18N
        CALCULATEBUTTON.setText("CALCULATE");
        CALCULATEBUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CALCULATEBUTTONActionPerformed(evt);
            }
        });
        jPanel1.add(CALCULATEBUTTON, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 420, -1, -1));

        MRADIO.setBackground(new java.awt.Color(0, 153, 255));
        buttonGroup1.add(MRADIO);
        MRADIO.setText("MALE");
        MRADIO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MRADIOActionPerformed(evt);
            }
        });
        jPanel1.add(MRADIO, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 360, 70, -1));

        FRADIO.setBackground(new java.awt.Color(0, 153, 255));
        buttonGroup1.add(FRADIO);
        FRADIO.setText("FEMALE");
        jPanel1.add(FRADIO, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 360, 80, -1));

        ANSWETEXTAREA.setColumns(20);
        ANSWETEXTAREA.setRows(5);
        jScrollPane2.setViewportView(ANSWETEXTAREA);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 160, 320, 360));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fitnesstrackerproject/dumbells.jpg"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1780, 900));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1599, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 903, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MRADIOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MRADIOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MRADIOActionPerformed

    private void CALCULATEBUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CALCULATEBUTTONActionPerformed
        String ageText = AGEFIELD.getText();
        String heightText = HEIGHTFIELD.getText();
        String weightText = WEIGHTFEILD.getText();
        boolean isMale = MRADIO.isSelected();

        if (ageText.isEmpty() || heightText.isEmpty() || weightText.isEmpty() || (!isMale && !FRADIO.isSelected())) {
            JOptionPane.showMessageDialog(null, "Please fill all fields and select gender.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            int age = Integer.parseInt(ageText);
            int height = Integer.parseInt(heightText);
            double weight = Double.parseDouble(weightText);

            CalorieCalculator calculator;

            if (isMale) {
                calculator = new MaleCalorieCalculator();
            } else {
                calculator = new FemaleCalorieCalculator();
            }

            double BMR = calculator.calculateBMR(weight, height, age);
            double TDEE = calculator.calculateTDEE(BMR);
            double weightLossCalories = TDEE - 500;
            double weightGainCalories = TDEE + 500;

            ANSWETEXTAREA.setText("Your daily calorie needs:" +
                "\nBMR: " + BMR + " calories/day" +
                "\nTDEE: " + TDEE + " calories/day" +
                "\nTo lose weight: " + weightLossCalories + " calories/day" +
                "\nTo gain weight: " + weightGainCalories + " calories/day" +
                "\n\nBMR: The energy your body uses at rest." +
                "\nTDEE: The total calories you burn in a day, including activity and digestion.");
            saveToDatabase(height, isMale ? "Male" : "Female", weight, age, BMR, TDEE);

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Please enter valid numbers for age, height, and weight.", "Input Error",
                JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "An unexpected error occurred: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_CALCULATEBUTTONActionPerformed

    private void WEIGHTFEILDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WEIGHTFEILDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WEIGHTFEILDActionPerformed

    private void bbuutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbuutonActionPerformed
        // TODO add your handling code here:
        GeneralFitnessPage form3 = new GeneralFitnessPage();

        form3.setVisible(true);
        dispose();
    }//GEN-LAST:event_bbuutonActionPerformed
private void saveToDatabase(int height, String gender, double weight, int age, double BMR, double TDEE) {
        String url = "jdbc:ucanaccess://C:/Users/HP/Desktop/Fitness Tracker.accdb";

        String sql = "INSERT INTO CALORIE (height, gender, weight, age, BMR, TDEE) VALUES (?, ?, ?, ?, ?, ?)";

        try (Connection conn = DriverManager.getConnection(url);
             PreparedStatement pstmt = conn.prepareStatement(sql)) {

            pstmt.setInt(1, height);
            pstmt.setString(2, gender);
            pstmt.setDouble(3, weight);
            pstmt.setInt(4, age);
            pstmt.setDouble(5, BMR);
            pstmt.setDouble(6, TDEE);

            pstmt.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data saved successfully!");

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error saving data: " + e.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
        }}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalorieAndBMI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalorieAndBMI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalorieAndBMI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalorieAndBMI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalorieAndBMI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AGEFIELD;
    private javax.swing.JTextArea ANSWETEXTAREA;
    private javax.swing.JButton CALCULATEBUTTON;
    private javax.swing.JRadioButton FRADIO;
    private javax.swing.JTextField HEIGHTFIELD;
    private javax.swing.JRadioButton MRADIO;
    private javax.swing.JTextField WEIGHTFEILD;
    private javax.swing.JButton bbuuton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
