/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fitnesstrackerproject;

/**
 *
 * @author hp
 */
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
public class GeneralFitnessPage extends javax.swing.JFrame {

    /**
     * Creates new form Form3
     */
    public GeneralFitnessPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        CC = new javax.swing.JButton();
        DE = new javax.swing.JButton();
        HC = new javax.swing.JButton();
        HYD = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Lucida Handwriting", 1, 10)); // NOI18N
        jLabel2.setText("CHOOSE :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 240, 115, -1));

        CC.setBackground(new java.awt.Color(0, 153, 255));
        CC.setFont(new java.awt.Font("Lucida Handwriting", 1, 14)); // NOI18N
        CC.setText("CALORIE COUNTER");
        CC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CCActionPerformed(evt);
            }
        });
        getContentPane().add(CC, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 340, 280, -1));

        DE.setBackground(new java.awt.Color(0, 153, 255));
        DE.setFont(new java.awt.Font("Lucida Handwriting", 1, 14)); // NOI18N
        DE.setText("DAILY EXERCISE");
        DE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DEActionPerformed(evt);
            }
        });
        getContentPane().add(DE, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 380, 280, -1));

        HC.setBackground(new java.awt.Color(0, 153, 255));
        HC.setFont(new java.awt.Font("Lucida Handwriting", 1, 14)); // NOI18N
        HC.setText("HEALTH CONCERNS");
        HC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HCActionPerformed(evt);
            }
        });
        getContentPane().add(HC, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 260, 280, -1));

        HYD.setBackground(new java.awt.Color(0, 153, 255));
        HYD.setFont(new java.awt.Font("Lucida Handwriting", 1, 14)); // NOI18N
        HYD.setText("HYDRATION CONTROLLER");
        HYD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HYDActionPerformed(evt);
            }
        });
        getContentPane().add(HYD, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 300, 280, -1));

        jButton2.setFont(new java.awt.Font("Lucida Handwriting", 1, 14)); // NOI18N
        jButton2.setText("BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 420, -1, -1));

        jLabel3.setFont(new java.awt.Font("Lucida Handwriting", 1, 14)); // NOI18N
        jLabel3.setText("                                          GENERAL FITNESS ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 210, 430, 38));

        jLabel1.setFont(new java.awt.Font("Lucida Handwriting", 1, 14)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fitnesstrackerproject/dumbells.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1620, 900));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CCActionPerformed
        // TODO add your handling code here,
        CalorieAndBMI form7 = new CalorieAndBMI();

        form7.setVisible(true);
        dispose();
    }//GEN-LAST:event_CCActionPerformed

    private void DEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DEActionPerformed
        // TODO add your handling code here:
        DailyExercise Form8 = new DailyExercise();

        Form8.setVisible(true);
        dispose();
    }//GEN-LAST:event_DEActionPerformed

    private void HCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HCActionPerformed
        // TODO add your handling code here:
        HealthCocerns form6 = new HealthCocerns();

        form6.setVisible(true);
        dispose();
    }//GEN-LAST:event_HCActionPerformed

    private void HYDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HYDActionPerformed
        // TODO add your handling code here:
        HydrationController form9 = new HydrationController();

        form9.setVisible(true);
        dispose();
    }//GEN-LAST:event_HYDActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new SelectionPage().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GeneralFitnessPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GeneralFitnessPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GeneralFitnessPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GeneralFitnessPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GeneralFitnessPage().setVisible(true);
            }
        });
    }
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CC;
    private javax.swing.JButton DE;
    private javax.swing.JButton HC;
    private javax.swing.JButton HYD;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
