/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fitnesstrackerproject;

/**
 *
 * @author hp
 */
public class HealthCocerns extends javax.swing.JFrame {

    /**
     * Creates new form Form6
     */
    public HealthCocerns() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        healthconcerns = new javax.swing.JLabel();
        bbutton = new javax.swing.JButton();
        jointpainbutton = new javax.swing.JButton();
        stressandanxietybutton = new javax.swing.JButton();
        nutritionaldefecienciesbutton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        answer2 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        healthconcerns.setFont(new java.awt.Font("Lucida Handwriting", 1, 14)); // NOI18N
        healthconcerns.setText("HEALTH CONCERNS:");
        getContentPane().add(healthconcerns, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 210, 180, 30));

        bbutton.setFont(new java.awt.Font("Lucida Handwriting", 1, 10)); // NOI18N
        bbutton.setText("BACK");
        bbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(bbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 420, -1, -1));

        jointpainbutton.setBackground(new java.awt.Color(255, 0, 51));
        jointpainbutton.setFont(new java.awt.Font("Lucida Handwriting", 0, 12)); // NOI18N
        jointpainbutton.setText("Joint Pain");
        jointpainbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jointpainbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(jointpainbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 390, 210, 30));

        stressandanxietybutton.setBackground(new java.awt.Color(255, 102, 0));
        stressandanxietybutton.setFont(new java.awt.Font("Lucida Handwriting", 0, 12)); // NOI18N
        stressandanxietybutton.setText(" Stress and Anxiety");
        stressandanxietybutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stressandanxietybuttonActionPerformed(evt);
            }
        });
        getContentPane().add(stressandanxietybutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 340, 210, 30));

        nutritionaldefecienciesbutton.setBackground(new java.awt.Color(0, 102, 255));
        nutritionaldefecienciesbutton.setFont(new java.awt.Font("Lucida Handwriting", 0, 12)); // NOI18N
        nutritionaldefecienciesbutton.setText("Nutritional Deficiencies");
        nutritionaldefecienciesbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nutritionaldefecienciesbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(nutritionaldefecienciesbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 290, 210, 30));

        answer2.setColumns(20);
        answer2.setRows(5);
        jScrollPane2.setViewportView(answer2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 190, 310, 270));

        jLabel2.setFont(new java.awt.Font("Lucida Handwriting", 0, 8)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fitnesstrackerproject/dumbells.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbuttonActionPerformed
        // TODO add your handling code here:
        GeneralFitnessPage form3 = new GeneralFitnessPage();

        form3.setVisible(true);
        dispose();
    }//GEN-LAST:event_bbuttonActionPerformed

    private void jointpainbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jointpainbuttonActionPerformed
        // TODO add your handling code here
        String message = "Recommended Exercises for Joint Pain:\n\n" +
        "Age 20-30:\n" +
        "Exercises:\nRunning, Cycling, Yoga\n" +
        "Recommended Time:\n30 minutes daily\n\n" +
        "Age 31-40:\n" +
        "Exercises:\nSwimming, Pilates, Stretching\n" +
        "Recommended Time:\n30-45 minutes daily\n\n" +
        "Age 41-50:\n" +
        "Exercises:\nWalking, Water Aerobics, Light Strength Training\n" +
        "Recommended Time:\n30 minutes daily\n\n" +
        "Age 51-60:\n" +
        "Exercises:\nTai Chi, Low-Impact Aerobics, Balance Exercises\n" +
        "Recommended Time:\n20-30 minutes daily\n";

        answer2.setText(message);
    }//GEN-LAST:event_jointpainbuttonActionPerformed

    private void stressandanxietybuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stressandanxietybuttonActionPerformed
        // TODO add your handling code here:        // TODO add your handling code here:
        String message = "Recommended Exercises :\n\n" +
        "Age 20-30:\n" +
        "Exercises:\nMeditation, Breathing Exercises, Yoga\n" +
        "Recommended Time:\n20-30 minutes daily\n\n" +
        "Age 31-40:\n" +
        "Exercises:\nMindfulness, Progressive Muscle Relaxation\n" +
        "Recommended Time:\n20-30 minutes daily\n\n" +
        "Age 41-50:\n" +
        "Exercises:\nGuided Imagery, Qi Gong, Journaling\n" +
        "Recommended Time:\n20-30 minutes daily\n\n" +
        "Age 51-60:\n" +
        "Exercises:\nDeep Breathing, Visualization, Gentle Stretching\n" +
        "Recommended Time:\n20-30 minutes daily\n";

        // Set the text in the JTextArea
        answer2.setText(message);
    }//GEN-LAST:event_stressandanxietybuttonActionPerformed

    private void nutritionaldefecienciesbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nutritionaldefecienciesbuttonActionPerformed
        String message = "Recommended Nutrition for Addressing Deficiencies:\n\n" +
        "Age 20-30:\n" +
        "Include in your diet:\n a.Leafy greens (spinach, kale)\nb.nuts and seeds (almonds, chia seeds)\nc.lean proteins (chicken, fish)\nd.dairy (yogurt, milk)\n" +
        "\nRecommended Daily Intake:\na.5 servings of fruits and vegetables\nb.2-3 servings of protein\nc.2-3 servings of dairy\n\n" +
        "Age 31-40:\n" +
        "Include in your diet:\na.Whole grains (quinoa, brown rice)\nb.legumes (beans, lentils)\nc.fruits (berries, citrus)\nd.vegetables (broccoli, bell peppers)\n" +
        "\nRecommended Daily Intake:\na.6-8 servings of grains\nb.3-4 servings of fruits\nc.4-5 servings of vegetables\n\n" +
        "Age 41-50:\n" +
        "Include in your diet:\na.Omega-3 fatty acids (salmon, walnuts)\nb.calcium-rich foods (cheese, fortified plant milk)\nc.iron-rich foods (lean red meat, tofu)\n" +
        "\nRecommended Daily Intake:\na.2 servings of fish\nb.3 servings of calcium-rich foods,\nc.2 servings of iron-rich foods\n\n" +
        "Age 51-60:\n" +
        "Include in your diet:\na.Fiber-rich foods (whole grains, legumes)\nb.antioxidants (blueberries, tomatoes)\nc.vitamin D sources (egg yolks)\n" +
        "\nRecommended Daily Intake:\na.6-8 servings of grains\nb.3-4 servings of fruits\nc.4-5 servings of vegetables\n";

        answer2.setText(message);
    }//GEN-LAST:event_nutritionaldefecienciesbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HealthCocerns.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HealthCocerns.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HealthCocerns.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HealthCocerns.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>


        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HealthCocerns().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea answer2;
    private javax.swing.JButton bbutton;
    private javax.swing.JLabel healthconcerns;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jointpainbutton;
    private javax.swing.JButton nutritionaldefecienciesbutton;
    private javax.swing.JButton stressandanxietybutton;
    // End of variables declaration//GEN-END:variables
}
