/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fitnesstrackerproject;

/**
 *
 * @author hp
 */
public class HydrationController extends javax.swing.JFrame {

    /**
     * Creates new form Form9
     */
    public HydrationController() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        NUMBEROFGLASSTEXTFIELD = new javax.swing.JTextField();
        CHECKBUTTON = new javax.swing.JButton();
        bbutton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        answertextarea = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Handwriting", 1, 14)); // NOI18N
        jLabel1.setText("HYDRATION CONTROLLER");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 220, 224, 28));

        jLabel2.setFont(new java.awt.Font("Lucida Handwriting", 1, 10)); // NOI18N
        jLabel2.setText(" ENTER THE NUMBER OF GLASSES YOU HAVE DRUNK TODAY");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 270, 350, 30));

        NUMBEROFGLASSTEXTFIELD.setFont(new java.awt.Font("Calibri", 1, 10)); // NOI18N
        NUMBEROFGLASSTEXTFIELD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NUMBEROFGLASSTEXTFIELDActionPerformed(evt);
            }
        });
        getContentPane().add(NUMBEROFGLASSTEXTFIELD, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 300, 70, 30));

        CHECKBUTTON.setFont(new java.awt.Font("Lucida Handwriting", 1, 10)); // NOI18N
        CHECKBUTTON.setText("CHECK");
        CHECKBUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CHECKBUTTONActionPerformed(evt);
            }
        });
        getContentPane().add(CHECKBUTTON, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 330, -1, -1));

        bbutton.setFont(new java.awt.Font("Lucida Handwriting", 1, 14)); // NOI18N
        bbutton.setForeground(new java.awt.Color(51, 51, 51));
        bbutton.setText("BACK");
        bbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(bbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 420, -1, -1));

        answertextarea.setColumns(20);
        answertextarea.setFont(new java.awt.Font("Calibri", 1, 10)); // NOI18N
        answertextarea.setRows(5);
        jScrollPane1.setViewportView(answertextarea);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 380, 300, 90));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fitnesstrackerproject/dumbells.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NUMBEROFGLASSTEXTFIELDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NUMBEROFGLASSTEXTFIELDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NUMBEROFGLASSTEXTFIELDActionPerformed

    private void CHECKBUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CHECKBUTTONActionPerformed
        answertextarea.setText("");

    String input = NUMBEROFGLASSTEXTFIELD.getText().trim();

    if (input.isEmpty()) {
        answertextarea.setText("Please enter the number of glasses you have drunk today.");
        return;
    }

    try {
        int numberOfGlasses = Integer.parseInt(input);
        if (numberOfGlasses > 12) {
            answertextarea.setText("Excellent!\nYou have drunk more than the recommended amount of water.\nKeep up the good work!");
        } else if (numberOfGlasses >= 8) {
            answertextarea.setText("Great job!\nYou have met the recommended daily water intake.\nStay hydrated and consider adding some lemon or lime to\nyour water for extra flavor and benefits.");
        } else {
            answertextarea.setText("You could use a few more glasses of water.\nStaying hydrated is important for your health.\nConsider having more water-rich fruits and vegetables.\nlike watermelon, oranges, or cucumbers.");
        }
    } catch (NumberFormatException e) {
        answertextarea.setText("Please enter a valid number.");
    
}
    }//GEN-LAST:event_CHECKBUTTONActionPerformed

    private void bbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbuttonActionPerformed
        // TODO add your handling code here:
        GeneralFitnessPage form3 = new GeneralFitnessPage();

        form3.setVisible(true);
        dispose();
    }//GEN-LAST:event_bbuttonActionPerformed

 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HydrationController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HydrationController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HydrationController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HydrationController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HydrationController().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CHECKBUTTON;
    private javax.swing.JTextField NUMBEROFGLASSTEXTFIELD;
    private javax.swing.JTextArea answertextarea;
    private javax.swing.JButton bbutton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
