/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fitnesstrackerproject;

import javax.swing.JFrame;
import javax.swing.JLabel;

/**
 *
 * @author hp
 */
public class SelectionPage extends javax.swing.JFrame {

    /**
     * Creates new form form2
     */
    public SelectionPage() {
        initComponents();
    }
      

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        generalfitnessbutton = new javax.swing.JButton();
        weightgainbutton = new javax.swing.JButton();
        weightlossbutton = new javax.swing.JButton();
        backbutton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(32767, 32767));
        jPanel1.setPreferredSize(new java.awt.Dimension(1336, 746));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 102));
        jLabel1.setText("Choose what you would like to do");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 800, 49));

        generalfitnessbutton.setBackground(new java.awt.Color(255, 0, 51));
        generalfitnessbutton.setFont(new java.awt.Font("Calisto MT", 1, 24)); // NOI18N
        generalfitnessbutton.setText("GENERAL FITNESS");
        generalfitnessbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generalfitnessbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(generalfitnessbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 260, 320, 70));

        weightgainbutton.setBackground(new java.awt.Color(255, 102, 0));
        weightgainbutton.setFont(new java.awt.Font("Calisto MT", 1, 24)); // NOI18N
        weightgainbutton.setText("WEIGHT GAIN");
        weightgainbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weightgainbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(weightgainbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 350, 320, 70));

        weightlossbutton.setBackground(new java.awt.Color(0, 51, 204));
        weightlossbutton.setFont(new java.awt.Font("Calisto MT", 1, 24)); // NOI18N
        weightlossbutton.setText("WEIGHT LOSS");
        weightlossbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weightlossbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(weightlossbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 440, 320, 80));

        backbutton.setBackground(new java.awt.Color(102, 0, 102));
        backbutton.setFont(new java.awt.Font("Lucida Handwriting", 1, 14)); // NOI18N
        backbutton.setForeground(new java.awt.Color(255, 255, 255));
        backbutton.setText("BACK");
        backbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(backbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 490, 110, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fitnesstrackerproject/dumbells.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1950, 900));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1600, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 900, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void weightgainbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weightgainbuttonActionPerformed
        // TODO add your handling code here:
        
      WeightGain form4 = new WeightGain();
    form4.setVisible(true);
    }//GEN-LAST:event_weightgainbuttonActionPerformed

    private void generalfitnessbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generalfitnessbuttonActionPerformed
        // TODO add your handling code here:
       GeneralFitnessPage form3 = new GeneralFitnessPage();
       form3.setVisible(true);
    dispose();
   
    }//GEN-LAST:event_generalfitnessbuttonActionPerformed

    private void weightlossbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weightlossbuttonActionPerformed
        // TODO add your handling code here:
        
        WeightLoss form5 = new WeightLoss();
       
    form5.setVisible(true);
    dispose();
     
    }//GEN-LAST:event_weightlossbuttonActionPerformed

    private void backbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbuttonActionPerformed
        // TODO add your handling code here:
        LoginPage Login = new LoginPage();
       
    Login.setVisible(true);
    dispose();
    }//GEN-LAST:event_backbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelectionPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelectionPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelectionPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelectionPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SelectionPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backbutton;
    private javax.swing.JButton generalfitnessbutton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton weightgainbutton;
    private javax.swing.JButton weightlossbutton;
    // End of variables declaration//GEN-END:variables
}
